### ISSUE TITLE
Better default formatting for dates

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#144]
This will probably go for all the various types of dates, date-times, times, etc.

``` r
library(cards)

ard_continuous(
  ADSL, 
  variables = DISONSDT, 
  statistics = ~continuous_variable_summary_fns(c("min", "max"))
)
#> {cards} data frame: 2 x 8
#>   variable   context stat_name stat_label statistic statistic_fmt_fn
#> 1 DISONSDT continuo…       min        Min     10390                1
#> 2 DISONSDT continuo…       max        Max     15964                1
#> ℹ 2 more variables: warning, error

ADSL$DISONSDT |> min()
#> [1] "1998-06-13"
```

<sup>Created on 2024-01-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Maybe just makes the class's formatting function `as.character()`?

**Comment by shajoezhu** [comment]
adding lubridate for dependencies?

**Comment by ddsjoberg** [comment]
> adding lubridate for dependencies?

Hmm, what do you have in mind, @shajoezhu ? Hopefully we can avoid new deps!

**Comment by shajoezhu** [comment]
> > adding lubridate for dependencies?
> 
> Hmm, what do you have in mind, @shajoezhu ? Hopefully we can avoid new deps!

Hi @ddsjoberg , I totally agree to keep the dependencies lean, in the past when we were dealing with real clinical data, we had to consider some date and time standardization due to timezone, or not labelled. lubridate can help and handle these case easily, so we included in tern. initially i thought this could be added to cardx as it is for analysis, but on seond sort, it we can standardize the date at the basic data structure layer, analysis would be easier? what do you think

**Comment by ddsjoberg** [comment]
@shajoezhu ahh, I see! That makes sense (although, I am not totally familiar with all the types of cases we may need to handle).

The package will still allow us to specify any function to format the results, which can be lubridate. But maybe we can keep the default as a Base R solution? 🤔  When you're back from the holiday, let's discuss use cases and we'll land on something that will work well.
