### ISSUE TITLE
set group name to group_level column

### ISSUE THREAD

**Issue by thebioengineer** [insightsengineering/cards#16]
### Feature description

When flattening a table, currently you preserve the grouping column as the `group#` value and `group_level#` as the actual value contained at that group. It would be nice to be able to have that handled such that the column value is applied to group_level after flattening - I think it would make it much easier to use.

Was there a reason for keeping group and group_level as separate?

**Comment by ddsjoberg** [comment]
hey hey! I haven't put too much consideration into what `flatten_ard()` should and shouldn't do...when I wrote it, I just wanted a quick way to see what is in the ARD. What you're suggesting is that after the flattening, the `group#_level` column should be renamed to the value of the `group#` column, like below if we were summarizing mtcars?

``` r
#> # A tibble: 3 × 1
#>     cyl
#>   <dbl>
#> 1     4
#> 2     6
#> 3     8
```

<sup>Created on 2023-09-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If I am interpreting your suggestion correctly, I agree it would certainly increase readability. The reason I would not do that is because we'd need to then introduce protected names. For example, users would not be able to tabulate by a column called `variable` or `statistic` as these already exist in the ARD. I know this would not happen in a proper ADaM set, but I like the ARD model, and I think of ways it would be applied outside of a strict data model like ADaM. 🤔 That said, absolutely something to think about. thanks for the post!

**Comment by ddsjoberg** [comment]
We're going to leave the current names as they are. But BK will write a function to output results in this format.
