### ISSUE TITLE
Add warning and error columns to `ard_attributes()` output

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#327]
``` r
cards::ard_attributes(cards::ADSL[c("AGE", "AGEGR1")])
#> {cards} data frame: 4 x 5
#>   variable   context stat_name stat_label      stat
#> 1      AGE attribut…     label  Variable…       Age
#> 2      AGE attribut…     class  Variable…   numeric
#> 3   AGEGR1 attribut…     label  Variable… Pooled A…
#> 4   AGEGR1 attribut…     class  Variable… character
```

<sup>Created on 2024-09-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
```r
dplyr::mutate(warning = list(NULL), error = list(NULL))
```

Also, add a unit test for the structure of the ARD using `check_ard_structure()`. (This test appears in other unit testing files FYI)

**Comment by jtalboys** [comment]
I can take this 😃

**Comment by jtalboys** [comment]
Hi @ddsjoberg, I've added the `warning` and `error` columns using the command you suggested. However, the `check_ard_structure()` test still fails as we're missing the `fmt_fn` column. Just wanted to check what should be expected here, either we also add the `fmt_fn` column to the output of `ard_attributes()` (also `NULL`, or `0`?) or we alter the check for `ard_attributes()` so that we don't expect `fmt_fn` to be present?

**Comment by ddsjoberg** [comment]
Ah, thank you @jtalboys ! The function was deficient in more ways that I realized 😆 

Can you add that column too? I think using `as.character` is a reasonable default?
